# -*- coding: utf-8 -*-
"""SQL Assignment

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/17wj-5wy0xHnZo6BDhHCJhmI7T8_aYv8K
"""

# Commented out IPython magic to ensure Python compatibility.
# %load_ext sql
# %sql sqlite://

"""Que 1. Create a table called employees with the following structure?
: emp_id (integer, should not be NULL and should be a primary key)Q
: emp_name (text, should not be NULL)Q
: age (integer, should have a check constraint to ensure the age is at least 18)Q
: email (text, should be unique for each employee)Q
: salary (decimal, with a default value of 30,000).

Write the SQL query to create the above table with all constraints
**bold text**
Ans:>
"""

# Commented out IPython magic to ensure Python compatibility.
# %%sql
# create table Employees(
#   Emp_id int primary key Not Null,
#   Emp_Name varchar(40) Not Null,
#   Age int check (age>=18),
#   Email varchar(50) unique,
#   Salary decimal(10,2) default 30000
# );

"""Que 2. Explain the purpose of constraints and how they help maintain data integrity in a database. Provide
examples of common types of constraints.

# **What Are Constraints in SQL?**

Constraints are rules applied to columns in a table to restrict the type of data that can be stored in them.

 Purpose: To enforce data integrity, prevent invalid data entry, and ensure database accuracy and reliability.

# How Constraints Help Maintain Data Integrity

Constraints:

Prevent duplicate or invalid values.

Ensure relationships between tables are valid.

Protect critical fields from being empty.

Enforce business rules, like minimum age or salary.

 # Common Types of SQL Constraints (with Examples)
 Below answer is constraint - purpose - example in this format.

1) PRIMARY KEY - Uniquely identifies each record - Emp_ID INTEGER PRIMARY KEY
2) NOT NULL - Prevents missing (null) values - Emp_Name VARCHAR(50) NOT NULL
3) UNIQUE - Ensures all values in a column are different - Email VARCHAR(100) UNIQUE
4) CHECK - Restricts values based on a condition - Age INTEGER CHECK (Age >= 18)
5) DEFAULT - Sets a default value if none is given - Salary DECIMAL(10,2) DEFAULT 30000
6) FOREIGN KEY - Links one table to another - Dept_ID INT, FOREIGN KEY (Dept_ID) REFERENCES Departments(ID)

Que 3.Why would you apply the NOT NULL constraint to a column? Can a primary key contain NULL values? Justify
# your answer.

# Why Apply the NOT NULL Constraint?
The NOT NULL constraint is used to ensure that a column must always have a value — i.e., it cannot be left blank or NULL.

# Reasons to Use NOT NULL:

*  Ensure essential data is present

→ Example: An employee's name or email should never be empty.

* Prevent accidental data loss or bugs

→ Blank values may cause errors or confusion in reports and calculations.

* Maintain data integrity

→ Forces the user or application to provide valid input every time.

# Can a Primary Key Contain NULL Values?
No. A primary key can NEVER contain NULL values.
# Rule /Justification of Primary Key:
It must be unique (no two rows have the same value).

It must be NOT NULL (value must be provided).


**Even if you don’t explicitly write NOT NULL, SQL automatically applies NOT NULL to the primary key.**
"""

# Commented out IPython magic to ensure Python compatibility.
# %%sql
# ---This will throw an error
# INSERT INTO Employees (Emp_ID, Emp_Name) VALUES (NULL, 'Nikita');
#

# Commented out IPython magic to ensure Python compatibility.
# %%sql
# --- this is the correct query
# create table employees_deatails(
#   Emp_id int primary key Not Null,
#   Emp_name varchar (35) Not null,
#   Email varchar(50) Not Null
# );
#

"""Que 4. Explain the steps and SQL commands used to add or remove constraints on an existing table. Provide an
example for both adding and removing a constraint.

# General Syntax:
ALTER TABLE table_name

ADD CONSTRAINT constraint_name constraint_type;
"""

# Commented out IPython magic to ensure Python compatibility.
# # suppose we have table
# %%sql
# CREATE TABLE Employees(
# 
#   Emp_ID INTEGER PRIMARY KEY,
#   Emp_Name VARCHAR(40),
#   Age INTEGER,
#   Email VARCHAR(50)
# );
#

# Commented out IPython magic to ensure Python compatibility.
# # now we want to add constraint
# # Now we want to add a CHECK and constraint to ensure age ≥ 18
# # Now we want to add a unique constraint to unique mail
# %%sql
# ALTER TABLE Employees
# ADD CONSTRAINT chk_age CHECK (Age >= 18);
# ADD CONSTRAINT unique_email UNIQUE (Email);
# 
# # this query give error because google colab does not support direct alter table constraints
#

# Commented out IPython magic to ensure Python compatibility.
# # so  we can do this
# %%sql
# 
# -- Step 1: Rename original table
# ALTER TABLE Employees RENAME TO Employees_old;
# 
# -- Step 2: Create new table with constraints
# CREATE TABLE Employees (
#   Emp_ID INTEGER PRIMARY KEY NOT NULL,
#   Emp_Name VARCHAR(40) NOT NULL,
#   Age INTEGER CHECK (Age >= 18),
#   Email VARCHAR(50) UNIQUE,
#   Salary DECIMAL(10,2) DEFAULT 30000
# );
# 
# -- Step 3: Copy data from old table to new table
# INSERT INTO Employees (Emp_ID, Emp_Name, Age, Email, Salary)
# SELECT Emp_ID, Emp_Name, Age, Email, Salary FROM Employees_old;
# 
# -- Step 4: Drop old table
# DROP TABLE Employees_old;
#

"""Que 5. Explain the consequences of attempting to insert, update, or delete data in a way that violates constraints.
Provide an example of an error message that might occur when violating a constraint.

# Consequences of Violating Constraints
When you try to insert, update, or delete data in a way that breaks a constraint, the database will block the action and show an error message.

This protects the database from corrupt or inconsistent data.
"""

# Commented out IPython magic to ensure Python compatibility.
# # consequences of attempting to insert
# %%sql
# INSERT INTO Employees (Emp_ID, Emp_Name, Age)
# VALUES (101, NULL, 25);
#

# Commented out IPython magic to ensure Python compatibility.
# # consequences of attempting to update
# %%sql
# UPDATE Employees
# SET Age = 15
# WHERE Emp_ID = 102;

"""# Constraint Violations - DELETE
DELETE usually doesn’t violate constraints unless:

There are foreign key dependencies (not in this table).

You delete a row expected by another table.


"""

# Commented out IPython magic to ensure Python compatibility.
# %%sql
# DELETE FROM Employees
# WHERE Emp_ID = 102;
#

"""Que 6. You created a products table without constraints as follows:

CREATE TABLE products (

    product_id INT,

    product_name VARCHAR(50),
    
    price DECIMAL(10, 2));

 Now, you realise that?
 The product_id should be a primary keyQ

 The price should have a default value of 50.00

  
"""

# Commented out IPython magic to ensure Python compatibility.
# %%sql
# CREATE TABLE products_ (
# 
# product_id INT,
# 
# product_name VARCHAR(50),
# 
# price DECIMAL(10, 2));
# 
#

# Commented out IPython magic to ensure Python compatibility.
# %%sql
# -- Add primary key constraint on product_id
# 
# ALTER TABLE products
# ADD PRIMARY KEY (product_id);
# 
# -- Set default value for price
# 
# ALTER TABLE products
# ALTER COLUMN price SET DEFAULT 50.00;
#

"""Que  7. You have two tables:
**Students Table:**

student_id | student_name | class_id
1 | Alice | 101
2 | Bob | 102
3 | Charlie | 101

**Classes Table:**

class_id | class_name
101 | Math
102 | Science
103 | History

Write an SQL query to fetch the student_name and class_name for each student using an INNER JOIN.



"""

# Commented out IPython magic to ensure Python compatibility.
# %%sql
# SELECT students.student_name, classes.class_name
# FROM students
# INNER JOIN classes ON students.class_id = classes.class_id;
#

"""Que 8. Consider the following three tables:

order_id | order_date | customer_id
12 | 2024-01-01 | 101
12 | 2024-01-03 | 102

customer_id | customer_name
101 | Alice
102 | Bob

product_id | product_name | order_id
1 | Laptop | 1
2 | Phone | NULL

Write a query that shows all order_id, customer_name, and product_name, ensuring that all products are
listed even if they are not associated with an order
Hint: (use INNER JOIN and LEFT JOIN)



"""

# Commented out IPython magic to ensure Python compatibility.
# %%sql
# select
# p.order_id,
# c.customer_name,
# p.product_name
# from products p left join orders
# on c.order_id =o.order_id
# left join customers
# on o.customer_id = c.customer_id;
# 
# 
#

"""Que 9. Given the following tables:

sale_id | product_id | amount
1 | 101 | 500
2 | 102 | 300
3 | 101 | 700

product_id | product_name
101 | Laptop
102 | Phone

Write a query to find the total sales amount for each product using an INNER JOIN and the SUM() function.
"""

# Commented out IPython magic to ensure Python compatibility.
# %%sql
# SELECT
#     p.product_name,
#     SUM(s.amount) AS total_sales
# FROM sales s
# INNER JOIN products p ON s.product_id = p.product_id
# GROUP BY p.product_name;
#

"""Que 10. You are given three tables:

order_id | order_date | customer_id
1 | 2024-01-02 | 1
2 | 2024-01-05 | 2

customer_id | customer_name
1 | Alice
2 | Bob

order_id | product_id | quantity
1 | 101 | 2
2 | 102 | 1
3 | 101 | 3

Write a query to display the order_id, customer_name, and the quantity of products ordered by each
customer using an INNER JOIN between all three tables.
But first give me structures of table and then answer

"""

# Commented out IPython magic to ensure Python compatibility.
# %%sql
# SELECT
#     o.order_id,
#     c.customer_name,
#     od.quantity
# FROM order_details od
# INNER JOIN orders o ON od.order_id = o.order_id
# INNER JOIN customers c ON o.customer_id = c.customer_id;
#

"""# SQL Commands


# Que 1- Identify the primary keys and foreign keys in maven movies db. Discuss the differences

# Primary Keys and Foreign Keys in the Maven Movies Database
In the context of a Maven Movies database, primary keys (PK) and foreign keys (FK) play crucial roles in defining data relationships and ensuring data integrity.

**Primary Keys (PK):**
A primary key is a unique identifier for each record in a table. It ensures that each record can be uniquely identified by its primary key column. Primary keys cannot contain NULL values, and each record must have a unique value for this key.

**In the Maven Movies database:**

**Movies Table:** MovieID is the primary key, uniquely identifying each movie.

**Directors Table:** DirectorID is the primary key, uniquely identifying each director.

**Actors Table:** ActorID is the primary key, uniquely identifying each actor.

**Foreign Keys (FK):**
A foreign key is a column (or set of columns) that creates a relationship between two tables. It references the primary key of another table, ensuring referential integrity between the tables. A foreign key allows a record in one table to be linked to a record in another table. Foreign keys can contain NULL values, indicating that a relationship is not mandatory for all records.

**In the Maven Movies database:**

**Movies Table:** DirectorID is a foreign key referencing the DirectorID in the Directors table, linking each movie to its director.

**MovieActors Table:** Both MovieID and ActorID are foreign keys. MovieID references the MovieID in the Movies table, and ActorID references the ActorID in the Actors table, establishing a many-to-many relationship between movies and actors.

# Differences Between Primary Keys and Foreign Keys:
Uniqueness: A primary key ensures that each value is unique within its table, while a foreign key can have repeated values.

Nullability: A primary key cannot have NULL values, whereas a foreign key can have NULL values.

Purpose: The primary key uniquely identifies records within its own table. The foreign key is used to establish and enforce relationships between tables.

Location: The primary key is located within the same table, while the foreign key references a primary key in another table.

By defining primary and foreign keys, the database maintains data integrity and establishes meaningful relationships between different entities like movies, directors, and actors.

Que 2- List all details of actors
"""

# Commented out IPython magic to ensure Python compatibility.
# %%sql
# select * from actors;

"""Que 3 -List all customer information from DB."""

# Commented out IPython magic to ensure Python compatibility.
# %%sql
# select * from customers;

"""Que 4 -List different countries."""

# Commented out IPython magic to ensure Python compatibility.
# %%sql
# SELECT DISTINCT country FROM country;

"""Que 5 -Display all active customers."""

# Commented out IPython magic to ensure Python compatibility.
# %%sql
# SELECT * FROM customer WHERE active = 1;

"""Que 6 -List of all rental IDs for customer with ID 1."""

# Commented out IPython magic to ensure Python compatibility.
# %%sql
# SELECT rental_id FROM rental WHERE customer_id = 1

"""Que 7 - Display all the films whose rental duration is greater than 5 ."""

# Commented out IPython magic to ensure Python compatibility.
# %%sql
# SELECT * FROM film WHERE rental_duration > 5;

"""Que 8 - List the total number of films whose replacement cost is greater than $15 and less than $20."""

# Commented out IPython magic to ensure Python compatibility.
# %%sql
# SELECT COUNT(*) AS total_films
# FROM film
# WHERE replacement_cost > 15 AND replacement_cost < 20;
#

"""Que 9 - Display the count of unique first names of actors."""

# Commented out IPython magic to ensure Python compatibility.
# %%sql
# SELECT COUNT(DISTINCT first_name) AS unique_first_names
# FROM actor;
#

"""Que 10- Display the first 10 records from the customer table ."""

# Commented out IPython magic to ensure Python compatibility.
# %%sql
# select * from customer
# limit 10;

"""Que 11 - Display the first 3 records from the customer table whose first name starts with ‘b’."""

# Commented out IPython magic to ensure Python compatibility.
# %%sql
# SELECT * FROM customer
# WHERE first_name LIKE 'B%'
# LIMIT 3;
#

"""Que 12 -Display the names of the first 5 movies which are rated as ‘G’."""

# Commented out IPython magic to ensure Python compatibility.
# %%sql
# SELECT title
# FROM film
# WHERE rating = 'G'
# LIMIT 5;
#

"""Que 13-Find all customers whose first name starts with "a"."""

# Commented out IPython magic to ensure Python compatibility.
# %%sql
# SELECT * FROM customer
# WHERE first_name LIKE 'A%';
#

"""Que 14- Find all customers whose first name ends with "a"."""

# Commented out IPython magic to ensure Python compatibility.
# %%sql
# SELECT * FROM customer
# WHERE first_name LIKE '%A';
#

"""Que 15- Display the list of first 4 cities which start and end with ‘a’ ."""

# Commented out IPython magic to ensure Python compatibility.
# %%sql
# SELECT city
# FROM city
# WHERE city LIKE 'A%a'
# LIMIT 4;
#

"""Que 16- Find all customers whose first name have "NI" in any position."""

# Commented out IPython magic to ensure Python compatibility.
# %%sql
# SELECT * FROM customer
# WHERE first_name LIKE '%NI%';
#

"""Que 17- Find all customers whose first name have "r" in the second position ."""

# Commented out IPython magic to ensure Python compatibility.
# %%sql
# SELECT * FROM customer
# WHERE first_name LIKE '_r%';
#

"""Que 18 - Find all customers whose first name starts with "a" and are at least 5 characters in length."""

# Commented out IPython magic to ensure Python compatibility.
# %%sql
# SELECT * FROM customer
# WHERE first_name LIKE 'A%' AND LENGTH(first_name) >= 5;
#

"""Que 19- Find all customers whose first name starts with "a" and ends with "o"."""

# Commented out IPython magic to ensure Python compatibility.
# %%sql
# SELECT * FROM customer
# WHERE first_name LIKE 'A%o';

"""Que 20 - Get the films with pg and pg-13 rating using IN operator."""

# Commented out IPython magic to ensure Python compatibility.
# %%sql
# SELECT * FROM film
# WHERE rating IN ('PG', 'PG-13');
#

"""Que 21 - Get the films with length between 50 to 100 using between operator."""

# Commented out IPython magic to ensure Python compatibility.
# %%sql
# SELECT * FROM film
# WHERE length BETWEEN 50 AND 100;
#

"""Que 22 - Get the top 50 actors using limit operator."""

# Commented out IPython magic to ensure Python compatibility.
# %%sql
# select * from actor
# limit 50;

"""Que 23 - Get the distinct film ids from inventory table."""

# Commented out IPython magic to ensure Python compatibility.
# %%sql
# SELECT DISTINCT film_id
# FROM inventory;
#

"""## **Functions Section**
# **Basic Aggregate Functions:**

Question 1:
Retrieve the total number of rentals made in the Sakila database.
Hint: Use the COUNT() function.
"""

# Commented out IPython magic to ensure Python compatibility.
# %%sql
# SELECT COUNT(*) AS total_rentals
# FROM rental;
#

"""Question 2:
Find the average rental duration (in days) of movies rented from the Sakila database.
Hint: Utilize the AVG() function.
"""

# Commented out IPython magic to ensure Python compatibility.
# %%sql
# SELECT AVG(rental_duration) AS average_rental_duration
# FROM film;
#

"""# **String Functions:**

Question 3:
Display the first name and last name of customers in uppercase.
Hint: Use the UPPER () function.
"""

# Commented out IPython magic to ensure Python compatibility.
# %%sql
# SELECT
# UPPER(first_name) AS uppercase_first_name,
# UPPER(last_name) AS uppercase_last_name
# FROM customer;

"""Question 4:

Extract the month from the rental date and display it alongside the rental ID.
Hint: Employ the MONTH() function.
"""

# Commented out IPython magic to ensure Python compatibility.
# %%sql
# SELECT rental_id, MONTH(rental_date) AS rental_month
# FROM rental;
#

"""# GROUP BY:
Question 5:
Retrieve the count of rentals for each customer (display customer ID and the count of rentals).
Hint: Use COUNT () in conjunction with GROUP BY.
"""

# Commented out IPython magic to ensure Python compatibility.
# %%sql
# SELECT customer_id, COUNT(*) AS rental_count
# FROM rental
# GROUP BY customer_id;
#

"""Question 6:
Find the total revenue generated by each store.
Hint: Combine SUM() and GROUP BY.
"""

# Commented out IPython magic to ensure Python compatibility.
# %%sql
# SELECT store_id, SUM(amount) AS total_revenue
# FROM payment
# GROUP BY store_id;
#

"""Question 7:
Determine the total number of rentals for each category of movies.
Hint: JOIN film_category, film, and rental tables, then use cOUNT () and GROUP BY.
"""

# Commented out IPython magic to ensure Python compatibility.
# %%sql
# SELECT fc.category_id, COUNT(r.rental_id) AS total_rentals
# FROM film_category fc
# JOIN inventory i ON fc.film_id = i.film_id
# JOIN rental r ON i.inventory_id = r.inventory_id
# GROUP BY fc.category_id;
#

"""Question 8:
Find the average rental rate of movies in each language.
Hint: JOIN film and language tables, then use AVG () and GROUP BY.
"""

# Commented out IPython magic to ensure Python compatibility.
# %%sql
# SELECT l.name AS language, AVG(f.rental_rate) AS average_rental_rate
# FROM film f
# JOIN language l ON f.language_id = l.language_id
# GROUP BY l.name;
#

"""# Joins Section
Questions 9 -
Display the title of the movie, customer s first name, and last name who rented it.
Hint: Use JOIN between the film, inventory, rental, and customer tables.
"""

# Commented out IPython magic to ensure Python compatibility.
# %%sql
# SELECT f.title, c.first_name, c.last_name
# FROM rental r
# JOIN inventory i ON r.inventory_id = i.inventory_id
# JOIN film f ON i.film_id = f.film_id
# JOIN customer c ON r.customer_id = c.customer_id;
#

"""Question 10:
Retrieve the names of all actors who have appeared in the film "Gone with the Wind."
Hint: Use JOIN between the film actor, film, and actor tables.
"""

# Commented out IPython magic to ensure Python compatibility.
# %%sql
# SELECT a.first_name, a.last_name
# FROM actor a
# JOIN film_actor fa ON a.actor_id = fa.actor_id
# JOIN film f ON fa.film_id = f.film_id
# WHERE f.title = 'Gone with the Wind';
#

"""Question 11:
Retrieve the customer names along with the total amount they've spent on rentals.
Hint: JOIN customer, payment, and rental tables, then use SUM() and GROUP BY.
"""

# Commented out IPython magic to ensure Python compatibility.
# %%sql
# SELECT c.first_name, c.last_name, SUM(p.amount) AS total_spent
# FROM customer c
# JOIN payment p ON c.customer_id = p.customer_id
# GROUP BY c.customer_id;
#

"""Question 12:
List the titles of movies rented by each customer in a particular city (e.g., 'London').
Hint: JOIN customer, address, city, rental, inventory, and film tables, then use GROUP BY.
"""

# Commented out IPython magic to ensure Python compatibility.
# %%sql
# SELECT c.first_name, c.last_name, f.title
# FROM customer c
# JOIN address a ON c.address_id = a.address_id
# JOIN city ci ON a.city_id = ci.city_id
# JOIN rental r ON c.customer_id = r.customer_id
# JOIN inventory i ON r.inventory_id = i.inventory_id
# JOIN film f ON i.film_id = f.film_id
# WHERE ci.city = 'London'
# GROUP BY c.customer_id, f.title;
#

"""# **Advanced Joins and GROUP BY:**

Question 13:
Display the top 5 rented movies along with the number of times they've been rented.
Hint: JOIN film, inventory, and rental tables, then use COUNT () and GROUP BY, and limit the results.
"""

# Commented out IPython magic to ensure Python compatibility.
# %%sql
# SELECT f.title, COUNT(r.rental_id) AS rental_count
# FROM film f
# JOIN inventory i ON f.film_id = i.film_id
# JOIN rental r ON i.inventory_id = r.inventory_id
# GROUP BY f.title
# ORDER BY rental_count DESC
# LIMIT 5;
#

"""Question 14:
Determine the customers who have rented movies from both stores (store ID 1 and store ID 2).
Hint: Use JOINS with rental, inventory, and customer tables and consider COUNT() and GROUP BY.
"""

# Commented out IPython magic to ensure Python compatibility.
# %%sql
# SELECT customer_id
# FROM rental r
# JOIN inventory i ON r.inventory_id = i.inventory_id
# GROUP BY customer_id
# HAVING COUNT(DISTINCT i.store_id) = 2;
#

"""# **Windows Function:**

Que 1. Rank the customers based on the total amount they've spent on rentals.
"""

# Commented out IPython magic to ensure Python compatibility.
# %%sql
# SELECT customer_id, SUM(amount) AS total_spent,
#        RANK() OVER (ORDER BY SUM(amount) DESC) AS rank
# FROM payment
# GROUP BY customer_id;
#

"""Que 2. Calculate the cumulative revenue generated by each film over time."""

# Commented out IPython magic to ensure Python compatibility.
# %%sql
# SELECT f.film_id, f.title, r.rental_date,
#        SUM(p.amount) OVER (PARTITION BY f.film_id ORDER BY r.rental_date) AS cumulative_revenue
# FROM film f
# JOIN inventory i ON f.film_id = i.film_id
# JOIN rental r ON i.inventory_id = r.inventory_id
# JOIN payment p ON r.rental_id = p.rental_id;
#

"""Que 3. Determine the average rental duration for each film, considering films with similar lengths."""

# Commented out IPython magic to ensure Python compatibility.
# %%sql
# SELECT f.film_id, f.title, f.length,
#        AVG(r.return_date - r.rental_date) OVER (PARTITION BY f.length) AS avg_rental_duration
# FROM film f
# JOIN inventory i ON f.film_id = i.film_id
# JOIN rental r ON i.inventory_id = r.inventory_id;
#

"""Que 4. Identify the top 3 films in each category based on their rental counts."""

# Commented out IPython magic to ensure Python compatibility.
# %%sql
# WITH rental_counts AS (
#     SELECT f.film_id, f.title, fc.category_id, COUNT(r.rental_id) AS rental_count,
#            RANK() OVER (PARTITION BY fc.category_id ORDER BY COUNT(r.rental_id) DESC) AS rnk
#     FROM film f
#     JOIN film_category fc ON f.film_id = fc.film_id
#     JOIN inventory i ON f.film_id = i.film_id
#     JOIN rental r ON i.inventory_id = r.inventory_id
#     GROUP BY f.film_id, fc.category_id
# )
# SELECT * FROM rental_counts WHERE rnk <= 3;
#

"""Que 5. Calculate the difference in rental counts between each customer's total rentals and the average rentals
across all customers.
"""

# Commented out IPython magic to ensure Python compatibility.
# %%sql
# WITH customer_rentals AS (
#     SELECT customer_id, COUNT(*) AS rental_count FROM rental GROUP BY customer_id
# ),
# avg_rentals AS (
#     SELECT AVG(rental_count) AS avg_count FROM customer_rentals
# )
# SELECT cr.customer_id, cr.rental_count, (cr.rental_count - ar.avg_count) AS diff_from_avg
# FROM customer_rentals cr, avg_rentals ar;
#

"""Que 6. Find the monthly revenue trend for the entire rental store over time."""

# Commented out IPython magic to ensure Python compatibility.
# %%sql
# SELECT DATE_TRUNC('month', payment_date) AS month, SUM(amount) AS revenue
# FROM payment
# GROUP BY month
# ORDER BY month;
#

"""Que 7. Identify the customers whose total spending on rentals falls within the top 20% of all customers."""

# Commented out IPython magic to ensure Python compatibility.
# %%sql
# WITH customer_spending AS (
#     SELECT customer_id, SUM(amount) AS total_spent
#     FROM payment
#     GROUP BY customer_id
# ),
# percentile_calc AS (
#     SELECT PERCENTILE_CONT(0.8) WITHIN GROUP (ORDER BY total_spent) AS top_20_threshold FROM customer_spending
# )
# SELECT cs.*
# FROM customer_spending cs, percentile_calc pc
# WHERE cs.total_spent >= pc.top_20_threshold;
#

"""Que 8. Calculate the running total of rentals per category, ordered by rental count."""

# Commented out IPython magic to ensure Python compatibility.
# %%sql
# WITH category_rentals AS (
#     SELECT c.name AS category, COUNT(r.rental_id) AS rental_count
#     FROM category c
#     JOIN film_category fc ON c.category_id = fc.category_id
#     JOIN film f ON f.film_id = fc.film_id
#     JOIN inventory i ON i.film_id = f.film_id
#     JOIN rental r ON r.inventory_id = i.inventory_id
#     GROUP BY c.name
# )
# SELECT category, rental_count,
#        SUM(rental_count) OVER (ORDER BY rental_count DESC) AS running_total
# FROM category_rentals;
#

"""Que 9. Find the films that have been rented less than the average rental count for their respective categories."""

# Commented out IPython magic to ensure Python compatibility.
# %%sql
# WITH category_avg AS (
#     SELECT fc.category_id, AVG(rental_count) AS avg_rentals
#     FROM (
#         SELECT f.film_id, fc.category_id, COUNT(r.rental_id) AS rental_count
#         FROM film f
#         JOIN film_category fc ON f.film_id = fc.film_id
#         JOIN inventory i ON i.film_id = f.film_id
#         JOIN rental r ON r.inventory_id = i.inventory_id
#         GROUP BY f.film_id, fc.category_id
#     ) sub
#     GROUP BY fc.category_id
# )
# SELECT sub.film_id, sub.category_id, sub.rental_count
# FROM (
#     SELECT f.film_id, fc.category_id, COUNT(r.rental_id) AS rental_count
#     FROM film f
#     JOIN film_category fc ON f.film_id = fc.film_id
#     JOIN inventory i ON i.film_id = f.film_id
#     JOIN rental r ON r.inventory_id = i.inventory_id
#     GROUP BY f.film_id, fc.category_id
# ) sub
# JOIN category_avg ca ON sub.category_id = ca.category_id
# WHERE sub.rental_count < ca.avg_rentals;
#

"""Que 10. Identify the top 5 months with the highest revenue and display the revenue generated in each month."""

# Commented out IPython magic to ensure Python compatibility.
# %%sql
# SELECT TO_CHAR(payment_date, 'YYYY-MM') AS month, SUM(amount) AS revenue
# FROM payment
# GROUP BY month
# ORDER BY revenue DESC
# LIMIT 5;
#

"""# Normalisation & CTE

**1. First Normal Form (1NF):**

a. Identify a table in the Sakila database that violates 1NF. Explain how you
would normalize it to achieve 1NF.

# Ans:> First Normal Form (1NF):
**Definition:**

A table is in First Normal Form (1NF) if:

All columns contain only atomic (indivisible) values.

There are no repeating groups or arrays in a single column.

Each record is unique.

Example: A denormalized "rental_summary" table

| customer_id | customer_name | rented_films                       |
|-------------|----------------|------------------------------------|
| 1           | John Doe       | "Shrek, Batman Begins, Toy Story" |
| 2           | Jane Smith     | "Inception, Matrix"               |

Here, the rented_films column stores multiple values (i.e., a list of films) in a single field, which violates 1NF because the values are not atomic.

**Violation of 1NF:**

The rented_films column contains comma-separated lists, which are non-atomic.

You cannot efficiently query or update individual films in this format.

# **How to normalize this table to achieve 1NF:**

We create a new table where each film rented is stored in a separate row:

**Normalized Rental Table (In 1NF):**

| customer_id | customer_name | rented_film       |
|-------------|----------------|-------------------|
| 1           | John Doe       | Shrek             |
| 1           | John Doe       | Batman Begins     |
| 1           | John Doe       | Toy Story         |
| 2           | Jane Smith     | Inception         |
| 2           | Jane Smith     | Matrix            |

Now:

Each column contains atomic values.

There are no repeating groups.

The table satisfies 1NF.

Que 2. Second Normal Form (2NF):

a. Choose a table in Sakila and describe how you would determine whether it is in 2NF.
If it violates 2NF, explain the steps to normalize it.

# **Ans:>**
 **What is Second Normal Form (2NF)?**

A table is in 2NF if:

It is already in 1NF (First Normal Form), and

There are no partial dependencies — i.e., no non-prime attribute depends only on part of a composite primary key.

**Suppose we have this badly designed table:**

film_rental_info (violates 2NF):
"""

CREATE TABLE film_rental_info (
    film_id INT,
    store_id INT,
    film_title VARCHAR(100),
    category_name VARCHAR(50),
    rental_rate DECIMAL(4,2),
    PRIMARY KEY (film_id, store_id)
);

"""Here:

film_id and store_id together form the composite primary key.

But:

film_title, category_name, and rental_rate depend only on film_id, not on store_id.

These are partial dependencies, so this table violates 2NF.

#  How to Normalize to 2NF:
Step 1: Split the table into two tables:

Table 1: film_details (stores film info)

"""

CREATE TABLE film_details (
    film_id INT PRIMARY KEY,
    film_title VARCHAR(100),
    category_name VARCHAR(50),
    rental_rate DECIMAL(4,2)
);

"""Table 2: film_store (only holds the relationship between film and store)"""

CREATE TABLE film_store (
    film_id INT,
    store_id INT,
    PRIMARY KEY (film_id, store_id),
    FOREIGN KEY (film_id) REFERENCES film_details(film_id)
);

"""Now:

film_details contains only attributes fully dependent on film_id.

film_store represents the many-to-many relationship.

No partial dependencies → Now in 2NF.

Que 3. Third Normal Form (3NF):
a. Identify a table in Sakila that violates 3NF. Describe the transitive dependencies
present and outline the steps to normalize the table to 3NF.


# Ans:>
**What is Third Normal Form (3NF)?**

A table is in 3NF if:

It is already in 2NF, and

It does not contain transitive dependencies — i.e., non-prime attributes should not depend on other non-prime attributes.

Let’s suppose we have a poorly designed version of the customer table like this:

 **Table: customer_info (violates 3NF)**
"""

CREATE TABLE customer_info (
    customer_id INT PRIMARY KEY,
    first_name VARCHAR(50),
    last_name VARCHAR(50),
    email VARCHAR(100),
    address VARCHAR(100),
    city VARCHAR(50),
    country VARCHAR(50)
);

"""**🔴 Transitive Dependencies:**

customer_id → address

address → city

city → country

Here:

country depends on city, and city depends on address, which depends on customer_id.

So, country and city are transitively dependent on the primary key (customer_id).

Thus, this table violates 3NF.

#  Steps to Normalize into 3NF:
Step 1: Break the transitive dependencies into separate tables.

Table 1: customer
"""

CREATE TABLE customer (
    customer_id INT PRIMARY KEY,
    first_name VARCHAR(50),
    last_name VARCHAR(50),
    email VARCHAR(100),
    address_id INT
);

"""Table 2: address"""

CREATE TABLE address (
    address_id INT PRIMARY KEY,
    address VARCHAR(100),
    city_id INT
);

"""Table 3: city"""

CREATE TABLE city (
    city_id INT PRIMARY KEY,
    city_name VARCHAR(50),
    country_id INT
);

"""Table 4: country"""

CREATE TABLE country (
    country_id INT PRIMARY KEY,
    country_name VARCHAR(50)
);

"""Now:

All non-prime attributes directly depend on their table's primary key.

No transitive dependencies.

This structure is in Third Normal Form (3NF).

Que 4. Normalization Process:
a. Take a specific table in Sakila and guide through the process of normalizing it from the initial
unnormalized form up to at least 2NF.

# Ans:>
# Let’s Use a Hypothetical Version of the Sakila rental Table (UNF)
# Unnormalized Form (UNF): rental_summary_unf
"""

CREATE TABLE rental_summary_unf (
    rental_id INT,
    customer_name VARCHAR(100),
    rented_films TEXT, -- Stores multiple film titles in one column (e.g., "Shrek, Matrix")
    rental_dates TEXT -- Stores multiple rental dates (e.g., "2024-01-01, 2024-01-05")
);

"""
Issues:
Multiple film titles in one column (rented_films) → Repeating groups

Multiple rental dates in one column → Not atomic

This table violates 1NF.

 # Step 1: Convert to First Normal Form (1NF)
➤ Goal: Ensure atomic values and remove repeating groups.
✔ Normalized Table: rental_summary_1nf


"""

CREATE TABLE rental_summary_1nf (
    rental_id INT,
    customer_name VARCHAR(100),
    film_title VARCHAR(100), -- One film per row
    rental_date DATE -- One rental date per row
);

"""
# Sample Data After 1NF:**

rental_id	customer_name	film_title	rental_date
1	John Doe	Shrek	2024-01-01
1	John Doe	Matrix	2024-01-05
2	Jane Smith	Inception	2024-01-02

Now, each column has atomic values, and the table is in 1NF.

# Step 2: Convert to Second Normal Form (2NF)

➤ Requirements:
Already in 1NF

Remove Partial Dependencies (attributes depending on only part of the composite primary key)

# Problem in 1NF:
customer_name depends only on rental_id, not on full combination (rental_id, film_title).

**✔ Split into Two Tables:**
 Table 1: rental_info


"""

CREATE TABLE rental_info (
    rental_id INT PRIMARY KEY,
    customer_name VARCHAR(100)
);

"""** Table 2: rental_details**"""

CREATE TABLE rental_details (
    rental_id INT,
    film_title VARCHAR(100),
    rental_date DATE,
    PRIMARY KEY (rental_id, film_title),
    FOREIGN KEY (rental_id) REFERENCES rental_info(rental_id)
);

"""# ** Now the design is in 2NF:**
No repeating groups

All non-key attributes fully depend on the primary key

Partial dependency (customer_name depending on rental_id only) is resolved

# 5. CTE Basics:
Que a. Write a query using a CTE to retrieve the distinct list of actor names and the number of films they
have acted in from the actor and film_actor tables.
"""

-- Using Common Table Expression (CTE)
WITH actor_film_count AS (
    SELECT
        a.actor_id,
        CONCAT(a.first_name, ' ', a.last_name) AS actor_name,
        COUNT(fa.film_id) AS film_count
    FROM actor a
    JOIN film_actor fa ON a.actor_id = fa.actor_id
    GROUP BY a.actor_id, a.first_name, a.last_name
)

SELECT * FROM actor_film_count
ORDER BY film_count DESC;

"""**Explanation:**

We use a CTE named actor_film_count to:

Join actor and film_actor tables.

Count how many films each actor has acted in.

Concatenate first_name and last_name for a complete name.

Finally, we select from the CTE and order results by film count (optional).

**Sample Output:**

| actor_id | actor_name        | film_count |
|----------|-------------------|------------|
| 1        | PENELOPE GUINESS  | 20         |
| 2        | NICK WAHLBERG     | 19         |
| ...      | ...               | ...        |

# 6. CTE with Joins:

Que a. Create a CTE that combines information from the film and language tables to display the film title,
language name, and rental rate.
"""

-- Common Table Expression to combine film and language data
WITH film_language_info AS (
    SELECT
        f.film_id,
        f.title AS film_title,
        l.name AS language_name,
        f.rental_rate
    FROM film f
    JOIN language l ON f.language_id = l.language_id
)

SELECT film_title, language_name, rental_rate
FROM film_language_info
ORDER BY film_title;

"""**Explanation:**

This CTE named film_language_info:

Joins the film table with the language table using language_id.

Selects the film title, language name, and rental rate.

The final SELECT fetches clean output for display or reporting.

 **Sample Output:**

 | film_title       | language_name | rental_rate |
|------------------|---------------|-------------|
| ACADEMY DINOSAUR | English       | 0.99        |
| ACE GOLDFINGER   | English       | 4.99        |
| ...              | ...           | ...         |

# 7. CTE for Aggregation:
a. Write a query using a CTE to find the total revenue generated by each customer (sum of payments)
from the customer and payment tables.
"""

-- Common Table Expression to calculate total revenue per customer
WITH customer_revenue AS (
    SELECT
        c.customer_id,
        CONCAT(c.first_name, ' ', c.last_name) AS customer_name,
        SUM(p.amount) AS total_revenue
    FROM customer c
    JOIN payment p ON c.customer_id = p.customer_id
    GROUP BY c.customer_id, c.first_name, c.last_name
)

SELECT *
FROM customer_revenue
ORDER BY total_revenue DESC;

"""Explanation:

The CTE customer_revenue:

Joins the customer and payment tables.

Aggregates (SUM) the amount of all payments made by each customer.

Groups by customer to compute total revenue per customer.

The final SELECT retrieves all customer names and their total revenue.

**Sample Output:**

| customer_id | customer_name    | total_revenue |
|-------------|------------------|----------------|
| 123         | MARY SMITH       | 180.00         |
| 456         | JOHN DOE         | 160.50         |
| ...         | ...              | ...            |

# 8. CTE with Window Functions:
a. Utilize a CTE with a window function to rank films based on their rental duration from the film table.
"""

-- Common Table Expression with a window function to rank films
WITH film_ranks AS (
    SELECT
        film_id,
        title,
        rental_duration,
        RANK() OVER (ORDER BY rental_duration DESC) AS rental_rank
    FROM film
)

SELECT *
FROM film_ranks
ORDER BY rental_rank;

"""Explanation:

The CTE film_ranks:

Retrieves film_id, title, and rental_duration from the film table.

Applies the RANK() window function to rank films in descending order of rental_duration.

The final SELECT lists all films with their rank based on rental duration.

** Sample Output:**

| film_id | title             | rental_duration | rental_rank |
|---------|-------------------|------------------|-------------|
| 15      | CASPER BANG       | 7                | 1           |
| 22      | DRAGON SQUAD      | 7                | 1           |
| 87      | MATRIX REVIVED    | 6                | 3           |
| ...     | ...               | ...              | ...         |

# 9. CTE and Filtering:
a. Create a CTE to list customers who have made more than two rentals, and then join this CTE with the
customer table to retrieve additional customer details.
"""

-- CTE to find customers with more than 2 rentals
WITH frequent_customers AS (
    SELECT
        customer_id,
        COUNT(rental_id) AS rental_count
    FROM rental
    GROUP BY customer_id
    HAVING COUNT(rental_id) > 2
)

-- Join with customer table to get additional details
SELECT
    fc.customer_id,
    CONCAT(c.first_name, ' ', c.last_name) AS customer_name,
    c.email,
    fc.rental_count
FROM frequent_customers fc
JOIN customer c ON fc.customer_id = c.customer_id
ORDER BY fc.rental_count DESC;

"""Explanation:

The CTE frequent_customers:

Groups the rental table by customer_id.

Filters customers with more than 2 rentals using the HAVING clause.

The final query joins this CTE with the customer table to get:

Full name,

Email,

Rental count.

 **Sample Output:**

 | customer_id | customer_name     | email                   | rental_count |
|-------------|-------------------|--------------------------|---------------|
| 105         | LISA MONROE       | lisa.monroe@sakilacustomer.org | 12        |
| 203         | JAMES BUTLER      | james.butler@sakilacustomer.org | 9         |
| ...         | ...               | ...                      | ...           |

# 10. CTE for Date Calculations:
a. Write a query using a CTE to find the total number of rentals made each month, considering the
rental_date from the rental table
"""

-- CTE to calculate total rentals per month
WITH monthly_rentals AS (
    SELECT
        DATE_FORMAT(rental_date, '%Y-%m') AS rental_month,
        COUNT(rental_id) AS total_rentals
    FROM rental
    GROUP BY DATE_FORMAT(rental_date, '%Y-%m')
)

SELECT *
FROM monthly_rentals
ORDER BY rental_month;

"""Explanation:

The CTE monthly_rentals:

Extracts the month and year from the rental_date using DATE_FORMAT('%Y-%m').

Counts how many rentals occurred in each month.

The final query returns the month and corresponding rental count, ordered chronologically.

Sample Output:

| rental_month | total_rentals |
|--------------|----------------|
| 2005-05      | 123            |
| 2005-06      | 421            |
| 2005-07      | 310            |
| ...          | ...            |

# 11. CTE and Self-Join:
a. Create a CTE to generate a report showing pairs of actors who have appeared in the same film
together, using the film_actor table.
"""

-- CTE to list all pairs of actors who appeared in the same film
WITH actor_pairs AS (
    SELECT
        fa1.film_id,
        fa1.actor_id AS actor1_id,
        fa2.actor_id AS actor2_id
    FROM film_actor fa1
    JOIN film_actor fa2
        ON fa1.film_id = fa2.film_id
        AND fa1.actor_id < fa2.actor_id
)

-- Final query joining actor names for better readability
SELECT
    ap.film_id,
    CONCAT(a1.first_name, ' ', a1.last_name) AS actor1_name,
    CONCAT(a2.first_name, ' ', a2.last_name) AS actor2_name
FROM actor_pairs ap
JOIN actor a1 ON ap.actor1_id = a1.actor_id
JOIN actor a2 ON ap.actor2_id = a2.actor_id
ORDER BY ap.film_id, actor1_name, actor2_name;

"""Explanation:

CTE actor_pairs:

Performs a self-join on the film_actor table to find actor pairs in the same film.

The condition fa1.actor_id < fa2.actor_id avoids duplicate and self-pairs.

The final SELECT:

Joins the actor table twice to retrieve full names of both actors in the pair.

Returns a list of film IDs with actor name pairs who appeared together.

 Sample Output:
 | film_id | actor1_name       | actor2_name       |
|---------|-------------------|-------------------|
| 1       | ADAM GRANT        | ED CHASE          |
| 1       | ADAM GRANT        | MARY KEENER       |
| 2       | CATE MCQUEEN      | TOM MCKELLEN      |
| ...     | ...               | ...               |

# 12. CTE for Recursive Search:
a. Implement a recursive CTE to find all employees in the staff table who report to a specific manager,
considering the reports_to column
"""

staff (
    staff_id INT PRIMARY KEY,
    first_name VARCHAR(50),
    last_name VARCHAR(50),
    reports_to INT  -- references staff_id of the manager
)

"""Ans:>

"""

-- Replace `1` with the staff_id of the manager you want to search under
WITH RECURSIVE staff_hierarchy AS (
    -- Anchor member: the top-level manager
    SELECT
        staff_id,
        first_name,
        last_name,
        reports_to
    FROM staff
    WHERE staff_id = 1  -- specific manager's ID

    UNION ALL

    -- Recursive member: find employees reporting to the current level
    SELECT
        s.staff_id,
        s.first_name,
        s.last_name,
        s.reports_to
    FROM staff s
    INNER JOIN staff_hierarchy sh ON s.reports_to = sh.staff_id
)

-- Final result
SELECT *
FROM staff_hierarchy;

"""Explanation:

The CTE staff_hierarchy starts from a specific manager (e.g., staff_id = 1).

The recursive part joins staff on reports_to, pulling in all employees who report up the chain.

This structure works even for multi-level hierarchies, showing all direct and indirect reports.

** Sample Output (Assumed):**

"""